echo "Uninstalling Edge"
takeown /f "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
takeown /f "C:\Program Files (x86)\Microsoft\Edge\Application"
takeown /f "C:\Program Files (x86)\Microsoft\EdgeCore"
takeown /f "C:\Program Files (x86)\Microsoft\EdgeUpdate"
takeown /f "C:\Program Files (x86)\Microsoft\EdgeWebView"
cd "C:\Program Files (x86)\Microsoft\"
rm "C:\Program Files (x86)\Microsoft\EdgeCore"
rm "C:\Program Files (x86)\Microsoft\EdgeUpdate"
rm "C:\Program Files (x86)\Microsoft\EdgeWebView"
cd "C:\Program Files (x86)\Microsoft\Edge\Application"
del msedge.exe
rm "C:\Users\Hari\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\Microsoft Edge.lnk"
rm "C:\Program Files (x86)\Microsoft\Edge\Application"
